// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGcasGroupUserRelation = "gcasGroupUserRelation"

// GcasGroupUserRelation mapped from table <gcasGroupUserRelation>
type GcasGroupUserRelation struct {
	GcasUserID string    `gorm:"column:gcasUserId;primaryKey" json:"gcasUserId"`
	GroupID    string    `gorm:"column:groupId;primaryKey" json:"groupId"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
	UserRoleID int32     `gorm:"column:userRoleId;not null" json:"userRoleId"`
}

// TableName GcasGroupUserRelation's table name
func (*GcasGroupUserRelation) TableName() string {
	return TableNameGcasGroupUserRelation
}
