// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGcasGroup = "gcasGroup"

// GcasGroup mapped from table <gcasGroup>
type GcasGroup struct {
	ID              string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	GroupCategoryID int32     `gorm:"column:groupCategoryId" json:"groupCategoryId"`
	GroupName       string    `gorm:"column:groupName;not null" json:"groupName"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt       time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName GcasGroup's table name
func (*GcasGroup) TableName() string {
	return TableNameGcasGroup
}
