// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGcasUser = "gcasUser"

// GcasUser mapped from table <gcasUser>
type GcasUser struct {
	ID                     string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	FamilyName             string    `gorm:"column:familyName;not null" json:"familyName"`
	GivenName              string    `gorm:"column:givenName;not null" json:"givenName"`
	MailAddress            string    `gorm:"column:mailAddress;not null" json:"mailAddress"`
	OrganizationCategoryID int32     `gorm:"column:organizationCategoryId" json:"organizationCategoryId"`
	CreatedAt              time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt              time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
	LastLoginAt            time.Time `gorm:"column:lastLoginAt" json:"lastLoginAt"`
}

// TableName GcasUser's table name
func (*GcasUser) TableName() string {
	return TableNameGcasUser
}
