// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGcasGroupSystemRelation = "gcasGroupSystemRelation"

// GcasGroupSystemRelation mapped from table <gcasGroupSystemRelation>
type GcasGroupSystemRelation struct {
	SystemID  string    `gorm:"column:systemId;primaryKey" json:"systemId"`
	GroupID   string    `gorm:"column:groupId;primaryKey" json:"groupId"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName GcasGroupSystemRelation's table name
func (*GcasGroupSystemRelation) TableName() string {
	return TableNameGcasGroupSystemRelation
}
