// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMLocalGovernment = "m_localGovernment"

// MLocalGovernment mapped from table <m_localGovernment>
type MLocalGovernment struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	PrefectureName     string    `gorm:"column:prefectureName;not null" json:"prefectureName"`
	CityName           string    `gorm:"column:cityName;not null" json:"cityName"`
	PrefectureNameKana string    `gorm:"column:prefectureNameKana;not null" json:"prefectureNameKana"`
	CityNameKana       string    `gorm:"column:cityNameKana;not null" json:"cityNameKana"`
	CreatedAt          time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt          time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName MLocalGovernment's table name
func (*MLocalGovernment) TableName() string {
	return TableNameMLocalGovernment
}
