// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMOrganizationCategory = "m_organizationCategory"

// MOrganizationCategory mapped from table <m_organizationCategory>
type MOrganizationCategory struct {
	ID                         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrganizationCategoryNameJa string    `gorm:"column:organizationCategoryNameJa;not null" json:"organizationCategoryNameJa"`
	OrganizationCategoryNameEn string    `gorm:"column:organizationCategoryNameEn;not null" json:"organizationCategoryNameEn"`
	CreatedAt                  time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt                  time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName MOrganizationCategory's table name
func (*MOrganizationCategory) TableName() string {
	return TableNameMOrganizationCategory
}
