// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMUserRole = "m_userRole"

// MUserRole mapped from table <m_userRole>
type MUserRole struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleNameJa string    `gorm:"column:roleNameJa;not null" json:"roleNameJa"`
	RoleNameEn string    `gorm:"column:roleNameEn;not null" json:"roleNameEn"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName MUserRole's table name
func (*MUserRole) TableName() string {
	return TableNameMUserRole
}
