// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID                            *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	ProjectName                   string     `gorm:"column:projectName;type:character varying(255);not null" json:"projectName"`
	LocalGovernmentID             string     `gorm:"column:localGovernmentId;type:character varying(6);not null" json:"localGovernmentId"`
	ProjectType                   string     `gorm:"column:projectType;type:character varying(255);not null" json:"projectType"`
	GovernmentCloudConnectionType string     `gorm:"column:governmentCloudConnectionType;type:character varying(255);not null" json:"governmentCloudConnectionType"`
	CreatedAt                     *time.Time `gorm:"column:createdAt;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt                     *time.Time `gorm:"column:updatedAt;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
	CorporateNumber               string     `gorm:"column:corporateNumber;type:character varying(13);not null" json:"corporateNumber"`
	VendorName                    string     `gorm:"column:vendorName;type:character varying(255);not null" json:"vendorName"`
	ServiceOutsourcingFee         *int32     `gorm:"column:serviceOutsourcingFee;type:integer" json:"serviceOutsourcingFee"`
	CloudUsageFee                 *int32     `gorm:"column:cloudUsageFee;type:integer" json:"cloudUsageFee"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
