// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectSystemRelation = "projectSystemRelation"

// ProjectSystemRelation mapped from table <projectSystemRelation>
type ProjectSystemRelation struct {
	ProjectID string    `gorm:"column:projectId;primaryKey" json:"projectId"`
	SystemID  string    `gorm:"column:systemId;primaryKey" json:"systemId"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName ProjectSystemRelation's table name
func (*ProjectSystemRelation) TableName() string {
	return TableNameProjectSystemRelation
}
