// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectCost = "projectCost"

// ProjectCost mapped from table <projectCost>
type ProjectCost struct {
	ProjectID string     `gorm:"column:projectId;type:uuid;primaryKey" json:"projectId"`
	Year      int32      `gorm:"column:year;type:integer;primaryKey" json:"year"`
	Cost      *int32     `gorm:"column:cost;type:integer" json:"cost"`
	CreatedAt *time.Time `gorm:"column:createdAt;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
}

// TableName ProjectCost's table name
func (*ProjectCost) TableName() string {
	return TableNameProjectCost
}
