// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectCost = "projectCost"

// ProjectCost mapped from table <projectCost>
type ProjectCost struct {
	ProjectID string    `gorm:"column:projectId;primaryKey" json:"projectId"`
	Year      int32     `gorm:"column:year;primaryKey" json:"year"`
	Cost      int32     `gorm:"column:cost" json:"cost"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
}

// TableName ProjectCost's table name
func (*ProjectCost) TableName() string {
	return TableNameProjectCost
}
