// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID                            string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ProjectName                   string    `gorm:"column:projectName;not null" json:"projectName"`
	LocalGovernmentID             string    `gorm:"column:localGovernmentId;not null" json:"localGovernmentId"`
	ProjectType                   string    `gorm:"column:projectType;not null" json:"projectType"`
	GovernmentCloudConnectionType string    `gorm:"column:governmentCloudConnectionType;not null" json:"governmentCloudConnectionType"`
	CreatedAt                     time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt                     time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
	CorporateNumber               string    `gorm:"column:corporateNumber;not null" json:"corporateNumber"`
	VendorName                    string    `gorm:"column:vendorName;not null" json:"vendorName"`
	ServiceOutsourcingFee         int32     `gorm:"column:serviceOutsourcingFee" json:"serviceOutsourcingFee"`
	CloudUsageFee                 int32     `gorm:"column:cloudUsageFee" json:"cloudUsageFee"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
