// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystem = "system"

// System mapped from table <system>
type System struct {
	ID                string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	SystemName        string    `gorm:"column:systemName;not null" json:"systemName"`
	LocalGovernmentID string    `gorm:"column:localGovernmentId" json:"localGovernmentId"`
	CreatedAt         time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	UpdatedAt         time.Time `gorm:"column:updatedAt;not null;default:now()" json:"updatedAt"`
	MailAddress       string    `gorm:"column:mailAddress;not null" json:"mailAddress"`
	Telephone         string    `gorm:"column:telephone" json:"telephone"`
	Remark            string    `gorm:"column:remark" json:"remark"`
}

// TableName System's table name
func (*System) TableName() string {
	return TableNameSystem
}
