// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type DrizzleDrizzleMigration struct {
	ID        int32         `json:"id"`
	Hash      string        `json:"hash"`
	CreatedAt sql.NullInt64 `json:"created_at"`
}

type GcasGroup struct {
	ID              uuid.UUID     `json:"id"`
	GroupCategoryId sql.NullInt32 `json:"groupCategoryId"`
	GroupName       string        `json:"groupName"`
	CreatedAt       time.Time     `json:"createdAt"`
	UpdatedAt       time.Time     `json:"updatedAt"`
}

type GcasGroupSystemRelation struct {
	SystemId  uuid.UUID `json:"systemId"`
	GroupId   uuid.UUID `json:"groupId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type GcasGroupUserRelation struct {
	GcasUserId uuid.UUID `json:"gcasUserId"`
	GroupId    uuid.UUID `json:"groupId"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	UserRoleId int32     `json:"userRoleId"`
}

type GcasUser struct {
	ID                     uuid.UUID     `json:"id"`
	FamilyName             string        `json:"familyName"`
	GivenName              string        `json:"givenName"`
	MailAddress            string        `json:"mailAddress"`
	OrganizationCategoryId sql.NullInt32 `json:"organizationCategoryId"`
	CreatedAt              time.Time     `json:"createdAt"`
	UpdatedAt              time.Time     `json:"updatedAt"`
	LastLoginAt            sql.NullTime  `json:"lastLoginAt"`
}

type MLocalGovernment struct {
	ID                 string    `json:"id"`
	PrefectureName     string    `json:"prefectureName"`
	CityName           string    `json:"cityName"`
	PrefectureNameKana string    `json:"prefectureNameKana"`
	CityNameKana       string    `json:"cityNameKana"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type MOrganizationCategory struct {
	ID                         int32     `json:"id"`
	OrganizationCategoryNameJa string    `json:"organizationCategoryNameJa"`
	OrganizationCategoryNameEn string    `json:"organizationCategoryNameEn"`
	CreatedAt                  time.Time `json:"createdAt"`
	UpdatedAt                  time.Time `json:"updatedAt"`
}

type MUserRole struct {
	ID         int32     `json:"id"`
	RoleNameJa string    `json:"roleNameJa"`
	RoleNameEn string    `json:"roleNameEn"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Project struct {
	ID                            uuid.UUID     `json:"id"`
	ProjectName                   string        `json:"projectName"`
	LocalGovernmentId             string        `json:"localGovernmentId"`
	ProjectType                   string        `json:"projectType"`
	GovernmentCloudConnectionType string        `json:"governmentCloudConnectionType"`
	CreatedAt                     time.Time     `json:"createdAt"`
	UpdatedAt                     time.Time     `json:"updatedAt"`
	CorporateNumber               string        `json:"corporateNumber"`
	VendorName                    string        `json:"vendorName"`
	ServiceOutsourcingFee         sql.NullInt32 `json:"serviceOutsourcingFee"`
	CloudUsageFee                 sql.NullInt32 `json:"cloudUsageFee"`
}

type ProjectCost struct {
	ProjectId uuid.UUID     `json:"projectId"`
	Year      int32         `json:"year"`
	Cost      sql.NullInt32 `json:"cost"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type ProjectSystemRelation struct {
	ProjectId uuid.UUID `json:"projectId"`
	SystemId  uuid.UUID `json:"systemId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type System struct {
	ID                uuid.UUID      `json:"id"`
	SystemName        string         `json:"systemName"`
	LocalGovernmentId sql.NullString `json:"localGovernmentId"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
	MailAddress       string         `json:"mailAddress"`
	Telephone         sql.NullString `json:"telephone"`
	Remark            sql.NullString `json:"remark"`
}

type SystemBasicInformation struct {
	ID                   uuid.UUID       `json:"id"`
	ProjectId            uuid.UUID       `json:"projectId"`
	CorporateNumber      string          `json:"corporateNumber"`
	VendorName           string          `json:"vendorName"`
	OperationStartDate   string          `json:"operationStartDate"`
	StandardizationTasks json.RawMessage `json:"standardizationTasks"`
	CreatedAt            time.Time       `json:"createdAt"`
	UpdatedAt            time.Time       `json:"updatedAt"`
}
