// Package appservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package appservice

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CommonError defines model for common.Error.
type CommonError struct {
	// Detail エラーの詳細説明
	Detail *string `json:"detail,omitempty"`

	// Errors フィールドごとの詳細エラーリスト（Validationとか）
	Errors *[]struct {
		// Field エラーが発生したフィールド名
		Field *string `json:"field,omitempty"`

		// Message フィールドに関連するエラーメッセージ
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`

	// Instance 問題の一意識別子 (URIなど)
	Instance *string `json:"instance,omitempty"`

	// Status HTTPステータスコード
	Status int32 `json:"status"`

	// Title エラーの短いタイトル
	Title string `json:"title"`

	// TraceId リクエストトレース用ID
	TraceId *string `json:"traceId,omitempty"`

	// Type 問題の種類を表すURI
	Type *string `json:"type,omitempty"`
}

// ModelHealthCheck defines model for model.HealthCheck.
type ModelHealthCheck struct {
	Status string `json:"status"`
}

// ModelSystem defines model for model.System.
type ModelSystem struct {
	// CreatedAt The timestamp when the system was created
	CreatedAt time.Time `json:"createdAt"`

	// Id The ID of the system
	Id openapi_types.UUID `json:"id"`

	// LocalGovernmentId The local government ID associated with the system
	LocalGovernmentId *string `json:"localGovernmentId"`

	// MailAddress The email address associated with the system
	MailAddress openapi_types.Email `json:"mailAddress"`

	// Remark Additional remarks or notes about the system
	Remark *string `json:"remark"`

	// SystemName The name of the system
	SystemName string `json:"systemName"`

	// Telephone The telephone number associated with the system
	Telephone *string `json:"telephone"`

	// UpdatedAt The timestamp when the system was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateSystemJSONBody defines parameters for CreateSystem.
type CreateSystemJSONBody struct {
	// CreatedAt The timestamp when the system was created
	CreatedAt time.Time `json:"createdAt"`

	// Id The ID of the system
	Id openapi_types.UUID `json:"id"`

	// LocalGovernmentId The local government ID associated with the system
	LocalGovernmentId *string `json:"localGovernmentId"`

	// MailAddress The email address associated with the system
	MailAddress openapi_types.Email `json:"mailAddress"`

	// Remark Additional remarks or notes about the system
	Remark *string `json:"remark"`

	// SystemName The name of the system
	SystemName string `json:"systemName"`

	// Telephone The telephone number associated with the system
	Telephone *string `json:"telephone"`

	// UpdatedAt The timestamp when the system was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// UpdateSystemJSONBody defines parameters for UpdateSystem.
type UpdateSystemJSONBody struct {
	// CreatedAt The timestamp when the system was created
	CreatedAt time.Time `json:"createdAt"`

	// Id The ID of the system
	Id openapi_types.UUID `json:"id"`

	// LocalGovernmentId The local government ID associated with the system
	LocalGovernmentId *string `json:"localGovernmentId"`

	// MailAddress The email address associated with the system
	MailAddress openapi_types.Email `json:"mailAddress"`

	// Remark Additional remarks or notes about the system
	Remark *string `json:"remark"`

	// SystemName The name of the system
	SystemName string `json:"systemName"`

	// Telephone The telephone number associated with the system
	Telephone *string `json:"telephone"`

	// UpdatedAt The timestamp when the system was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateSystemJSONRequestBody defines body for CreateSystem for application/json ContentType.
type CreateSystemJSONRequestBody CreateSystemJSONBody

// UpdateSystemJSONRequestBody defines body for UpdateSystem for application/json ContentType.
type UpdateSystemJSONRequestBody UpdateSystemJSONBody
