// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newGcasGroupUserRelation(db *gorm.DB, opts ...gen.DOOption) gcasGroupUserRelation {
	_gcasGroupUserRelation := gcasGroupUserRelation{}

	_gcasGroupUserRelation.gcasGroupUserRelationDo.UseDB(db, opts...)
	_gcasGroupUserRelation.gcasGroupUserRelationDo.UseModel(&model.GcasGroupUserRelation{})

	tableName := _gcasGroupUserRelation.gcasGroupUserRelationDo.TableName()
	_gcasGroupUserRelation.ALL = field.NewAsterisk(tableName)
	_gcasGroupUserRelation.GcasUserID = field.NewString(tableName, "gcasUserId")
	_gcasGroupUserRelation.GroupID = field.NewString(tableName, "groupId")
	_gcasGroupUserRelation.CreatedAt = field.NewTime(tableName, "createdAt")
	_gcasGroupUserRelation.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_gcasGroupUserRelation.UserRoleID = field.NewInt32(tableName, "userRoleId")

	_gcasGroupUserRelation.fillFieldMap()

	return _gcasGroupUserRelation
}

type gcasGroupUserRelation struct {
	gcasGroupUserRelationDo gcasGroupUserRelationDo

	ALL        field.Asterisk
	GcasUserID field.String
	GroupID    field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time
	UserRoleID field.Int32

	fieldMap map[string]field.Expr
}

func (g gcasGroupUserRelation) Table(newTableName string) *gcasGroupUserRelation {
	g.gcasGroupUserRelationDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gcasGroupUserRelation) As(alias string) *gcasGroupUserRelation {
	g.gcasGroupUserRelationDo.DO = *(g.gcasGroupUserRelationDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gcasGroupUserRelation) updateTableName(table string) *gcasGroupUserRelation {
	g.ALL = field.NewAsterisk(table)
	g.GcasUserID = field.NewString(table, "gcasUserId")
	g.GroupID = field.NewString(table, "groupId")
	g.CreatedAt = field.NewTime(table, "createdAt")
	g.UpdatedAt = field.NewTime(table, "updatedAt")
	g.UserRoleID = field.NewInt32(table, "userRoleId")

	g.fillFieldMap()

	return g
}

func (g *gcasGroupUserRelation) WithContext(ctx context.Context) *gcasGroupUserRelationDo {
	return g.gcasGroupUserRelationDo.WithContext(ctx)
}

func (g gcasGroupUserRelation) TableName() string { return g.gcasGroupUserRelationDo.TableName() }

func (g gcasGroupUserRelation) Alias() string { return g.gcasGroupUserRelationDo.Alias() }

func (g gcasGroupUserRelation) Columns(cols ...field.Expr) gen.Columns {
	return g.gcasGroupUserRelationDo.Columns(cols...)
}

func (g *gcasGroupUserRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gcasGroupUserRelation) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["gcasUserId"] = g.GcasUserID
	g.fieldMap["groupId"] = g.GroupID
	g.fieldMap["createdAt"] = g.CreatedAt
	g.fieldMap["updatedAt"] = g.UpdatedAt
	g.fieldMap["userRoleId"] = g.UserRoleID
}

func (g gcasGroupUserRelation) clone(db *gorm.DB) gcasGroupUserRelation {
	g.gcasGroupUserRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gcasGroupUserRelation) replaceDB(db *gorm.DB) gcasGroupUserRelation {
	g.gcasGroupUserRelationDo.ReplaceDB(db)
	return g
}

type gcasGroupUserRelationDo struct{ gen.DO }

func (g gcasGroupUserRelationDo) Debug() *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Debug())
}

func (g gcasGroupUserRelationDo) WithContext(ctx context.Context) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gcasGroupUserRelationDo) ReadDB() *gcasGroupUserRelationDo {
	return g.Clauses(dbresolver.Read)
}

func (g gcasGroupUserRelationDo) WriteDB() *gcasGroupUserRelationDo {
	return g.Clauses(dbresolver.Write)
}

func (g gcasGroupUserRelationDo) Session(config *gorm.Session) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Session(config))
}

func (g gcasGroupUserRelationDo) Clauses(conds ...clause.Expression) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gcasGroupUserRelationDo) Returning(value interface{}, columns ...string) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gcasGroupUserRelationDo) Not(conds ...gen.Condition) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gcasGroupUserRelationDo) Or(conds ...gen.Condition) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gcasGroupUserRelationDo) Select(conds ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gcasGroupUserRelationDo) Where(conds ...gen.Condition) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gcasGroupUserRelationDo) Order(conds ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gcasGroupUserRelationDo) Distinct(cols ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gcasGroupUserRelationDo) Omit(cols ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gcasGroupUserRelationDo) Join(table schema.Tabler, on ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gcasGroupUserRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gcasGroupUserRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gcasGroupUserRelationDo) Group(cols ...field.Expr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gcasGroupUserRelationDo) Having(conds ...gen.Condition) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gcasGroupUserRelationDo) Limit(limit int) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gcasGroupUserRelationDo) Offset(offset int) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gcasGroupUserRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gcasGroupUserRelationDo) Unscoped() *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gcasGroupUserRelationDo) Create(values ...*model.GcasGroupUserRelation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gcasGroupUserRelationDo) CreateInBatches(values []*model.GcasGroupUserRelation, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gcasGroupUserRelationDo) Save(values ...*model.GcasGroupUserRelation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gcasGroupUserRelationDo) First() (*model.GcasGroupUserRelation, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupUserRelation), nil
	}
}

func (g gcasGroupUserRelationDo) Take() (*model.GcasGroupUserRelation, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupUserRelation), nil
	}
}

func (g gcasGroupUserRelationDo) Last() (*model.GcasGroupUserRelation, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupUserRelation), nil
	}
}

func (g gcasGroupUserRelationDo) Find() ([]*model.GcasGroupUserRelation, error) {
	result, err := g.DO.Find()
	return result.([]*model.GcasGroupUserRelation), err
}

func (g gcasGroupUserRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GcasGroupUserRelation, err error) {
	buf := make([]*model.GcasGroupUserRelation, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gcasGroupUserRelationDo) FindInBatches(result *[]*model.GcasGroupUserRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gcasGroupUserRelationDo) Attrs(attrs ...field.AssignExpr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gcasGroupUserRelationDo) Assign(attrs ...field.AssignExpr) *gcasGroupUserRelationDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gcasGroupUserRelationDo) Joins(fields ...field.RelationField) *gcasGroupUserRelationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gcasGroupUserRelationDo) Preload(fields ...field.RelationField) *gcasGroupUserRelationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gcasGroupUserRelationDo) FirstOrInit() (*model.GcasGroupUserRelation, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupUserRelation), nil
	}
}

func (g gcasGroupUserRelationDo) FirstOrCreate() (*model.GcasGroupUserRelation, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupUserRelation), nil
	}
}

func (g gcasGroupUserRelationDo) FindByPage(offset int, limit int) (result []*model.GcasGroupUserRelation, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gcasGroupUserRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gcasGroupUserRelationDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gcasGroupUserRelationDo) Delete(models ...*model.GcasGroupUserRelation) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gcasGroupUserRelationDo) withDO(do gen.Dao) *gcasGroupUserRelationDo {
	g.DO = *do.(*gen.DO)
	return g
}
