// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newGcasGroupSystemRelation(db *gorm.DB, opts ...gen.DOOption) gcasGroupSystemRelation {
	_gcasGroupSystemRelation := gcasGroupSystemRelation{}

	_gcasGroupSystemRelation.gcasGroupSystemRelationDo.UseDB(db, opts...)
	_gcasGroupSystemRelation.gcasGroupSystemRelationDo.UseModel(&model.GcasGroupSystemRelation{})

	tableName := _gcasGroupSystemRelation.gcasGroupSystemRelationDo.TableName()
	_gcasGroupSystemRelation.ALL = field.NewAsterisk(tableName)
	_gcasGroupSystemRelation.SystemID = field.NewString(tableName, "systemId")
	_gcasGroupSystemRelation.GroupID = field.NewString(tableName, "groupId")
	_gcasGroupSystemRelation.CreatedAt = field.NewTime(tableName, "createdAt")
	_gcasGroupSystemRelation.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_gcasGroupSystemRelation.fillFieldMap()

	return _gcasGroupSystemRelation
}

type gcasGroupSystemRelation struct {
	gcasGroupSystemRelationDo gcasGroupSystemRelationDo

	ALL       field.Asterisk
	SystemID  field.String
	GroupID   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (g gcasGroupSystemRelation) Table(newTableName string) *gcasGroupSystemRelation {
	g.gcasGroupSystemRelationDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gcasGroupSystemRelation) As(alias string) *gcasGroupSystemRelation {
	g.gcasGroupSystemRelationDo.DO = *(g.gcasGroupSystemRelationDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gcasGroupSystemRelation) updateTableName(table string) *gcasGroupSystemRelation {
	g.ALL = field.NewAsterisk(table)
	g.SystemID = field.NewString(table, "systemId")
	g.GroupID = field.NewString(table, "groupId")
	g.CreatedAt = field.NewTime(table, "createdAt")
	g.UpdatedAt = field.NewTime(table, "updatedAt")

	g.fillFieldMap()

	return g
}

func (g *gcasGroupSystemRelation) WithContext(ctx context.Context) *gcasGroupSystemRelationDo {
	return g.gcasGroupSystemRelationDo.WithContext(ctx)
}

func (g gcasGroupSystemRelation) TableName() string { return g.gcasGroupSystemRelationDo.TableName() }

func (g gcasGroupSystemRelation) Alias() string { return g.gcasGroupSystemRelationDo.Alias() }

func (g gcasGroupSystemRelation) Columns(cols ...field.Expr) gen.Columns {
	return g.gcasGroupSystemRelationDo.Columns(cols...)
}

func (g *gcasGroupSystemRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gcasGroupSystemRelation) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["systemId"] = g.SystemID
	g.fieldMap["groupId"] = g.GroupID
	g.fieldMap["createdAt"] = g.CreatedAt
	g.fieldMap["updatedAt"] = g.UpdatedAt
}

func (g gcasGroupSystemRelation) clone(db *gorm.DB) gcasGroupSystemRelation {
	g.gcasGroupSystemRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gcasGroupSystemRelation) replaceDB(db *gorm.DB) gcasGroupSystemRelation {
	g.gcasGroupSystemRelationDo.ReplaceDB(db)
	return g
}

type gcasGroupSystemRelationDo struct{ gen.DO }

func (g gcasGroupSystemRelationDo) Debug() *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Debug())
}

func (g gcasGroupSystemRelationDo) WithContext(ctx context.Context) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gcasGroupSystemRelationDo) ReadDB() *gcasGroupSystemRelationDo {
	return g.Clauses(dbresolver.Read)
}

func (g gcasGroupSystemRelationDo) WriteDB() *gcasGroupSystemRelationDo {
	return g.Clauses(dbresolver.Write)
}

func (g gcasGroupSystemRelationDo) Session(config *gorm.Session) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Session(config))
}

func (g gcasGroupSystemRelationDo) Clauses(conds ...clause.Expression) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gcasGroupSystemRelationDo) Returning(value interface{}, columns ...string) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gcasGroupSystemRelationDo) Not(conds ...gen.Condition) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gcasGroupSystemRelationDo) Or(conds ...gen.Condition) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gcasGroupSystemRelationDo) Select(conds ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gcasGroupSystemRelationDo) Where(conds ...gen.Condition) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gcasGroupSystemRelationDo) Order(conds ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gcasGroupSystemRelationDo) Distinct(cols ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gcasGroupSystemRelationDo) Omit(cols ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gcasGroupSystemRelationDo) Join(table schema.Tabler, on ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gcasGroupSystemRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gcasGroupSystemRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gcasGroupSystemRelationDo) Group(cols ...field.Expr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gcasGroupSystemRelationDo) Having(conds ...gen.Condition) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gcasGroupSystemRelationDo) Limit(limit int) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gcasGroupSystemRelationDo) Offset(offset int) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gcasGroupSystemRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gcasGroupSystemRelationDo) Unscoped() *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gcasGroupSystemRelationDo) Create(values ...*model.GcasGroupSystemRelation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gcasGroupSystemRelationDo) CreateInBatches(values []*model.GcasGroupSystemRelation, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gcasGroupSystemRelationDo) Save(values ...*model.GcasGroupSystemRelation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gcasGroupSystemRelationDo) First() (*model.GcasGroupSystemRelation, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupSystemRelation), nil
	}
}

func (g gcasGroupSystemRelationDo) Take() (*model.GcasGroupSystemRelation, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupSystemRelation), nil
	}
}

func (g gcasGroupSystemRelationDo) Last() (*model.GcasGroupSystemRelation, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupSystemRelation), nil
	}
}

func (g gcasGroupSystemRelationDo) Find() ([]*model.GcasGroupSystemRelation, error) {
	result, err := g.DO.Find()
	return result.([]*model.GcasGroupSystemRelation), err
}

func (g gcasGroupSystemRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GcasGroupSystemRelation, err error) {
	buf := make([]*model.GcasGroupSystemRelation, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gcasGroupSystemRelationDo) FindInBatches(result *[]*model.GcasGroupSystemRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gcasGroupSystemRelationDo) Attrs(attrs ...field.AssignExpr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gcasGroupSystemRelationDo) Assign(attrs ...field.AssignExpr) *gcasGroupSystemRelationDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gcasGroupSystemRelationDo) Joins(fields ...field.RelationField) *gcasGroupSystemRelationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gcasGroupSystemRelationDo) Preload(fields ...field.RelationField) *gcasGroupSystemRelationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gcasGroupSystemRelationDo) FirstOrInit() (*model.GcasGroupSystemRelation, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupSystemRelation), nil
	}
}

func (g gcasGroupSystemRelationDo) FirstOrCreate() (*model.GcasGroupSystemRelation, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroupSystemRelation), nil
	}
}

func (g gcasGroupSystemRelationDo) FindByPage(offset int, limit int) (result []*model.GcasGroupSystemRelation, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gcasGroupSystemRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gcasGroupSystemRelationDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gcasGroupSystemRelationDo) Delete(models ...*model.GcasGroupSystemRelation) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gcasGroupSystemRelationDo) withDO(do gen.Dao) *gcasGroupSystemRelationDo {
	g.DO = *do.(*gen.DO)
	return g
}
