// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newGcasUser(db *gorm.DB, opts ...gen.DOOption) gcasUser {
	_gcasUser := gcasUser{}

	_gcasUser.gcasUserDo.UseDB(db, opts...)
	_gcasUser.gcasUserDo.UseModel(&model.GcasUser{})

	tableName := _gcasUser.gcasUserDo.TableName()
	_gcasUser.ALL = field.NewAsterisk(tableName)
	_gcasUser.ID = field.NewString(tableName, "id")
	_gcasUser.FamilyName = field.NewString(tableName, "familyName")
	_gcasUser.GivenName = field.NewString(tableName, "givenName")
	_gcasUser.MailAddress = field.NewString(tableName, "mailAddress")
	_gcasUser.OrganizationCategoryID = field.NewInt32(tableName, "organizationCategoryId")
	_gcasUser.CreatedAt = field.NewTime(tableName, "createdAt")
	_gcasUser.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_gcasUser.LastLoginAt = field.NewTime(tableName, "lastLoginAt")

	_gcasUser.fillFieldMap()

	return _gcasUser
}

type gcasUser struct {
	gcasUserDo gcasUserDo

	ALL                    field.Asterisk
	ID                     field.String
	FamilyName             field.String
	GivenName              field.String
	MailAddress            field.String
	OrganizationCategoryID field.Int32
	CreatedAt              field.Time
	UpdatedAt              field.Time
	LastLoginAt            field.Time

	fieldMap map[string]field.Expr
}

func (g gcasUser) Table(newTableName string) *gcasUser {
	g.gcasUserDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gcasUser) As(alias string) *gcasUser {
	g.gcasUserDo.DO = *(g.gcasUserDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gcasUser) updateTableName(table string) *gcasUser {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewString(table, "id")
	g.FamilyName = field.NewString(table, "familyName")
	g.GivenName = field.NewString(table, "givenName")
	g.MailAddress = field.NewString(table, "mailAddress")
	g.OrganizationCategoryID = field.NewInt32(table, "organizationCategoryId")
	g.CreatedAt = field.NewTime(table, "createdAt")
	g.UpdatedAt = field.NewTime(table, "updatedAt")
	g.LastLoginAt = field.NewTime(table, "lastLoginAt")

	g.fillFieldMap()

	return g
}

func (g *gcasUser) WithContext(ctx context.Context) *gcasUserDo { return g.gcasUserDo.WithContext(ctx) }

func (g gcasUser) TableName() string { return g.gcasUserDo.TableName() }

func (g gcasUser) Alias() string { return g.gcasUserDo.Alias() }

func (g gcasUser) Columns(cols ...field.Expr) gen.Columns { return g.gcasUserDo.Columns(cols...) }

func (g *gcasUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gcasUser) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["familyName"] = g.FamilyName
	g.fieldMap["givenName"] = g.GivenName
	g.fieldMap["mailAddress"] = g.MailAddress
	g.fieldMap["organizationCategoryId"] = g.OrganizationCategoryID
	g.fieldMap["createdAt"] = g.CreatedAt
	g.fieldMap["updatedAt"] = g.UpdatedAt
	g.fieldMap["lastLoginAt"] = g.LastLoginAt
}

func (g gcasUser) clone(db *gorm.DB) gcasUser {
	g.gcasUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gcasUser) replaceDB(db *gorm.DB) gcasUser {
	g.gcasUserDo.ReplaceDB(db)
	return g
}

type gcasUserDo struct{ gen.DO }

func (g gcasUserDo) Debug() *gcasUserDo {
	return g.withDO(g.DO.Debug())
}

func (g gcasUserDo) WithContext(ctx context.Context) *gcasUserDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gcasUserDo) ReadDB() *gcasUserDo {
	return g.Clauses(dbresolver.Read)
}

func (g gcasUserDo) WriteDB() *gcasUserDo {
	return g.Clauses(dbresolver.Write)
}

func (g gcasUserDo) Session(config *gorm.Session) *gcasUserDo {
	return g.withDO(g.DO.Session(config))
}

func (g gcasUserDo) Clauses(conds ...clause.Expression) *gcasUserDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gcasUserDo) Returning(value interface{}, columns ...string) *gcasUserDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gcasUserDo) Not(conds ...gen.Condition) *gcasUserDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gcasUserDo) Or(conds ...gen.Condition) *gcasUserDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gcasUserDo) Select(conds ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gcasUserDo) Where(conds ...gen.Condition) *gcasUserDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gcasUserDo) Order(conds ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gcasUserDo) Distinct(cols ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gcasUserDo) Omit(cols ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gcasUserDo) Join(table schema.Tabler, on ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gcasUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gcasUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gcasUserDo) Group(cols ...field.Expr) *gcasUserDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gcasUserDo) Having(conds ...gen.Condition) *gcasUserDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gcasUserDo) Limit(limit int) *gcasUserDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gcasUserDo) Offset(offset int) *gcasUserDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gcasUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gcasUserDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gcasUserDo) Unscoped() *gcasUserDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gcasUserDo) Create(values ...*model.GcasUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gcasUserDo) CreateInBatches(values []*model.GcasUser, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gcasUserDo) Save(values ...*model.GcasUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gcasUserDo) First() (*model.GcasUser, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasUser), nil
	}
}

func (g gcasUserDo) Take() (*model.GcasUser, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasUser), nil
	}
}

func (g gcasUserDo) Last() (*model.GcasUser, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasUser), nil
	}
}

func (g gcasUserDo) Find() ([]*model.GcasUser, error) {
	result, err := g.DO.Find()
	return result.([]*model.GcasUser), err
}

func (g gcasUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GcasUser, err error) {
	buf := make([]*model.GcasUser, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gcasUserDo) FindInBatches(result *[]*model.GcasUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gcasUserDo) Attrs(attrs ...field.AssignExpr) *gcasUserDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gcasUserDo) Assign(attrs ...field.AssignExpr) *gcasUserDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gcasUserDo) Joins(fields ...field.RelationField) *gcasUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gcasUserDo) Preload(fields ...field.RelationField) *gcasUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gcasUserDo) FirstOrInit() (*model.GcasUser, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasUser), nil
	}
}

func (g gcasUserDo) FirstOrCreate() (*model.GcasUser, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasUser), nil
	}
}

func (g gcasUserDo) FindByPage(offset int, limit int) (result []*model.GcasUser, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gcasUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gcasUserDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gcasUserDo) Delete(models ...*model.GcasUser) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gcasUserDo) withDO(do gen.Dao) *gcasUserDo {
	g.DO = *do.(*gen.DO)
	return g
}
