// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newGcasGroup(db *gorm.DB, opts ...gen.DOOption) gcasGroup {
	_gcasGroup := gcasGroup{}

	_gcasGroup.gcasGroupDo.UseDB(db, opts...)
	_gcasGroup.gcasGroupDo.UseModel(&model.GcasGroup{})

	tableName := _gcasGroup.gcasGroupDo.TableName()
	_gcasGroup.ALL = field.NewAsterisk(tableName)
	_gcasGroup.ID = field.NewString(tableName, "id")
	_gcasGroup.GroupCategoryID = field.NewInt32(tableName, "groupCategoryId")
	_gcasGroup.GroupName = field.NewString(tableName, "groupName")
	_gcasGroup.CreatedAt = field.NewTime(tableName, "createdAt")
	_gcasGroup.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_gcasGroup.fillFieldMap()

	return _gcasGroup
}

type gcasGroup struct {
	gcasGroupDo gcasGroupDo

	ALL             field.Asterisk
	ID              field.String
	GroupCategoryID field.Int32
	GroupName       field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (g gcasGroup) Table(newTableName string) *gcasGroup {
	g.gcasGroupDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gcasGroup) As(alias string) *gcasGroup {
	g.gcasGroupDo.DO = *(g.gcasGroupDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gcasGroup) updateTableName(table string) *gcasGroup {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewString(table, "id")
	g.GroupCategoryID = field.NewInt32(table, "groupCategoryId")
	g.GroupName = field.NewString(table, "groupName")
	g.CreatedAt = field.NewTime(table, "createdAt")
	g.UpdatedAt = field.NewTime(table, "updatedAt")

	g.fillFieldMap()

	return g
}

func (g *gcasGroup) WithContext(ctx context.Context) *gcasGroupDo {
	return g.gcasGroupDo.WithContext(ctx)
}

func (g gcasGroup) TableName() string { return g.gcasGroupDo.TableName() }

func (g gcasGroup) Alias() string { return g.gcasGroupDo.Alias() }

func (g gcasGroup) Columns(cols ...field.Expr) gen.Columns { return g.gcasGroupDo.Columns(cols...) }

func (g *gcasGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gcasGroup) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["id"] = g.ID
	g.fieldMap["groupCategoryId"] = g.GroupCategoryID
	g.fieldMap["groupName"] = g.GroupName
	g.fieldMap["createdAt"] = g.CreatedAt
	g.fieldMap["updatedAt"] = g.UpdatedAt
}

func (g gcasGroup) clone(db *gorm.DB) gcasGroup {
	g.gcasGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gcasGroup) replaceDB(db *gorm.DB) gcasGroup {
	g.gcasGroupDo.ReplaceDB(db)
	return g
}

type gcasGroupDo struct{ gen.DO }

func (g gcasGroupDo) Debug() *gcasGroupDo {
	return g.withDO(g.DO.Debug())
}

func (g gcasGroupDo) WithContext(ctx context.Context) *gcasGroupDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gcasGroupDo) ReadDB() *gcasGroupDo {
	return g.Clauses(dbresolver.Read)
}

func (g gcasGroupDo) WriteDB() *gcasGroupDo {
	return g.Clauses(dbresolver.Write)
}

func (g gcasGroupDo) Session(config *gorm.Session) *gcasGroupDo {
	return g.withDO(g.DO.Session(config))
}

func (g gcasGroupDo) Clauses(conds ...clause.Expression) *gcasGroupDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gcasGroupDo) Returning(value interface{}, columns ...string) *gcasGroupDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gcasGroupDo) Not(conds ...gen.Condition) *gcasGroupDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gcasGroupDo) Or(conds ...gen.Condition) *gcasGroupDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gcasGroupDo) Select(conds ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gcasGroupDo) Where(conds ...gen.Condition) *gcasGroupDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gcasGroupDo) Order(conds ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gcasGroupDo) Distinct(cols ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gcasGroupDo) Omit(cols ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gcasGroupDo) Join(table schema.Tabler, on ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gcasGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gcasGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gcasGroupDo) Group(cols ...field.Expr) *gcasGroupDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gcasGroupDo) Having(conds ...gen.Condition) *gcasGroupDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gcasGroupDo) Limit(limit int) *gcasGroupDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gcasGroupDo) Offset(offset int) *gcasGroupDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gcasGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gcasGroupDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gcasGroupDo) Unscoped() *gcasGroupDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gcasGroupDo) Create(values ...*model.GcasGroup) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gcasGroupDo) CreateInBatches(values []*model.GcasGroup, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gcasGroupDo) Save(values ...*model.GcasGroup) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gcasGroupDo) First() (*model.GcasGroup, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroup), nil
	}
}

func (g gcasGroupDo) Take() (*model.GcasGroup, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroup), nil
	}
}

func (g gcasGroupDo) Last() (*model.GcasGroup, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroup), nil
	}
}

func (g gcasGroupDo) Find() ([]*model.GcasGroup, error) {
	result, err := g.DO.Find()
	return result.([]*model.GcasGroup), err
}

func (g gcasGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GcasGroup, err error) {
	buf := make([]*model.GcasGroup, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gcasGroupDo) FindInBatches(result *[]*model.GcasGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gcasGroupDo) Attrs(attrs ...field.AssignExpr) *gcasGroupDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gcasGroupDo) Assign(attrs ...field.AssignExpr) *gcasGroupDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gcasGroupDo) Joins(fields ...field.RelationField) *gcasGroupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gcasGroupDo) Preload(fields ...field.RelationField) *gcasGroupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gcasGroupDo) FirstOrInit() (*model.GcasGroup, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroup), nil
	}
}

func (g gcasGroupDo) FirstOrCreate() (*model.GcasGroup, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GcasGroup), nil
	}
}

func (g gcasGroupDo) FindByPage(offset int, limit int) (result []*model.GcasGroup, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gcasGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gcasGroupDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gcasGroupDo) Delete(models ...*model.GcasGroup) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gcasGroupDo) withDO(do gen.Dao) *gcasGroupDo {
	g.DO = *do.(*gen.DO)
	return g
}
