// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newMLocalGovernment(db *gorm.DB, opts ...gen.DOOption) mLocalGovernment {
	_mLocalGovernment := mLocalGovernment{}

	_mLocalGovernment.mLocalGovernmentDo.UseDB(db, opts...)
	_mLocalGovernment.mLocalGovernmentDo.UseModel(&model.MLocalGovernment{})

	tableName := _mLocalGovernment.mLocalGovernmentDo.TableName()
	_mLocalGovernment.ALL = field.NewAsterisk(tableName)
	_mLocalGovernment.ID = field.NewString(tableName, "id")
	_mLocalGovernment.PrefectureName = field.NewString(tableName, "prefectureName")
	_mLocalGovernment.CityName = field.NewString(tableName, "cityName")
	_mLocalGovernment.PrefectureNameKana = field.NewString(tableName, "prefectureNameKana")
	_mLocalGovernment.CityNameKana = field.NewString(tableName, "cityNameKana")
	_mLocalGovernment.CreatedAt = field.NewTime(tableName, "createdAt")
	_mLocalGovernment.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_mLocalGovernment.fillFieldMap()

	return _mLocalGovernment
}

type mLocalGovernment struct {
	mLocalGovernmentDo mLocalGovernmentDo

	ALL                field.Asterisk
	ID                 field.String
	PrefectureName     field.String
	CityName           field.String
	PrefectureNameKana field.String
	CityNameKana       field.String
	CreatedAt          field.Time
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (m mLocalGovernment) Table(newTableName string) *mLocalGovernment {
	m.mLocalGovernmentDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mLocalGovernment) As(alias string) *mLocalGovernment {
	m.mLocalGovernmentDo.DO = *(m.mLocalGovernmentDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mLocalGovernment) updateTableName(table string) *mLocalGovernment {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.PrefectureName = field.NewString(table, "prefectureName")
	m.CityName = field.NewString(table, "cityName")
	m.PrefectureNameKana = field.NewString(table, "prefectureNameKana")
	m.CityNameKana = field.NewString(table, "cityNameKana")
	m.CreatedAt = field.NewTime(table, "createdAt")
	m.UpdatedAt = field.NewTime(table, "updatedAt")

	m.fillFieldMap()

	return m
}

func (m *mLocalGovernment) WithContext(ctx context.Context) *mLocalGovernmentDo {
	return m.mLocalGovernmentDo.WithContext(ctx)
}

func (m mLocalGovernment) TableName() string { return m.mLocalGovernmentDo.TableName() }

func (m mLocalGovernment) Alias() string { return m.mLocalGovernmentDo.Alias() }

func (m mLocalGovernment) Columns(cols ...field.Expr) gen.Columns {
	return m.mLocalGovernmentDo.Columns(cols...)
}

func (m *mLocalGovernment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mLocalGovernment) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.ID
	m.fieldMap["prefectureName"] = m.PrefectureName
	m.fieldMap["cityName"] = m.CityName
	m.fieldMap["prefectureNameKana"] = m.PrefectureNameKana
	m.fieldMap["cityNameKana"] = m.CityNameKana
	m.fieldMap["createdAt"] = m.CreatedAt
	m.fieldMap["updatedAt"] = m.UpdatedAt
}

func (m mLocalGovernment) clone(db *gorm.DB) mLocalGovernment {
	m.mLocalGovernmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mLocalGovernment) replaceDB(db *gorm.DB) mLocalGovernment {
	m.mLocalGovernmentDo.ReplaceDB(db)
	return m
}

type mLocalGovernmentDo struct{ gen.DO }

func (m mLocalGovernmentDo) Debug() *mLocalGovernmentDo {
	return m.withDO(m.DO.Debug())
}

func (m mLocalGovernmentDo) WithContext(ctx context.Context) *mLocalGovernmentDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mLocalGovernmentDo) ReadDB() *mLocalGovernmentDo {
	return m.Clauses(dbresolver.Read)
}

func (m mLocalGovernmentDo) WriteDB() *mLocalGovernmentDo {
	return m.Clauses(dbresolver.Write)
}

func (m mLocalGovernmentDo) Session(config *gorm.Session) *mLocalGovernmentDo {
	return m.withDO(m.DO.Session(config))
}

func (m mLocalGovernmentDo) Clauses(conds ...clause.Expression) *mLocalGovernmentDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mLocalGovernmentDo) Returning(value interface{}, columns ...string) *mLocalGovernmentDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mLocalGovernmentDo) Not(conds ...gen.Condition) *mLocalGovernmentDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mLocalGovernmentDo) Or(conds ...gen.Condition) *mLocalGovernmentDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mLocalGovernmentDo) Select(conds ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mLocalGovernmentDo) Where(conds ...gen.Condition) *mLocalGovernmentDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mLocalGovernmentDo) Order(conds ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mLocalGovernmentDo) Distinct(cols ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mLocalGovernmentDo) Omit(cols ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mLocalGovernmentDo) Join(table schema.Tabler, on ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mLocalGovernmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mLocalGovernmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mLocalGovernmentDo) Group(cols ...field.Expr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mLocalGovernmentDo) Having(conds ...gen.Condition) *mLocalGovernmentDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mLocalGovernmentDo) Limit(limit int) *mLocalGovernmentDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mLocalGovernmentDo) Offset(offset int) *mLocalGovernmentDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mLocalGovernmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mLocalGovernmentDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mLocalGovernmentDo) Unscoped() *mLocalGovernmentDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mLocalGovernmentDo) Create(values ...*model.MLocalGovernment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mLocalGovernmentDo) CreateInBatches(values []*model.MLocalGovernment, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mLocalGovernmentDo) Save(values ...*model.MLocalGovernment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mLocalGovernmentDo) First() (*model.MLocalGovernment, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MLocalGovernment), nil
	}
}

func (m mLocalGovernmentDo) Take() (*model.MLocalGovernment, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MLocalGovernment), nil
	}
}

func (m mLocalGovernmentDo) Last() (*model.MLocalGovernment, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MLocalGovernment), nil
	}
}

func (m mLocalGovernmentDo) Find() ([]*model.MLocalGovernment, error) {
	result, err := m.DO.Find()
	return result.([]*model.MLocalGovernment), err
}

func (m mLocalGovernmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MLocalGovernment, err error) {
	buf := make([]*model.MLocalGovernment, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mLocalGovernmentDo) FindInBatches(result *[]*model.MLocalGovernment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mLocalGovernmentDo) Attrs(attrs ...field.AssignExpr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mLocalGovernmentDo) Assign(attrs ...field.AssignExpr) *mLocalGovernmentDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mLocalGovernmentDo) Joins(fields ...field.RelationField) *mLocalGovernmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mLocalGovernmentDo) Preload(fields ...field.RelationField) *mLocalGovernmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mLocalGovernmentDo) FirstOrInit() (*model.MLocalGovernment, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MLocalGovernment), nil
	}
}

func (m mLocalGovernmentDo) FirstOrCreate() (*model.MLocalGovernment, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MLocalGovernment), nil
	}
}

func (m mLocalGovernmentDo) FindByPage(offset int, limit int) (result []*model.MLocalGovernment, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mLocalGovernmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mLocalGovernmentDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mLocalGovernmentDo) Delete(models ...*model.MLocalGovernment) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mLocalGovernmentDo) withDO(do gen.Dao) *mLocalGovernmentDo {
	m.DO = *do.(*gen.DO)
	return m
}
