// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newMOrganizationCategory(db *gorm.DB, opts ...gen.DOOption) mOrganizationCategory {
	_mOrganizationCategory := mOrganizationCategory{}

	_mOrganizationCategory.mOrganizationCategoryDo.UseDB(db, opts...)
	_mOrganizationCategory.mOrganizationCategoryDo.UseModel(&model.MOrganizationCategory{})

	tableName := _mOrganizationCategory.mOrganizationCategoryDo.TableName()
	_mOrganizationCategory.ALL = field.NewAsterisk(tableName)
	_mOrganizationCategory.ID = field.NewInt32(tableName, "id")
	_mOrganizationCategory.OrganizationCategoryNameJa = field.NewString(tableName, "organizationCategoryNameJa")
	_mOrganizationCategory.OrganizationCategoryNameEn = field.NewString(tableName, "organizationCategoryNameEn")
	_mOrganizationCategory.CreatedAt = field.NewTime(tableName, "createdAt")
	_mOrganizationCategory.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_mOrganizationCategory.fillFieldMap()

	return _mOrganizationCategory
}

type mOrganizationCategory struct {
	mOrganizationCategoryDo mOrganizationCategoryDo

	ALL                        field.Asterisk
	ID                         field.Int32
	OrganizationCategoryNameJa field.String
	OrganizationCategoryNameEn field.String
	CreatedAt                  field.Time
	UpdatedAt                  field.Time

	fieldMap map[string]field.Expr
}

func (m mOrganizationCategory) Table(newTableName string) *mOrganizationCategory {
	m.mOrganizationCategoryDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mOrganizationCategory) As(alias string) *mOrganizationCategory {
	m.mOrganizationCategoryDo.DO = *(m.mOrganizationCategoryDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mOrganizationCategory) updateTableName(table string) *mOrganizationCategory {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.OrganizationCategoryNameJa = field.NewString(table, "organizationCategoryNameJa")
	m.OrganizationCategoryNameEn = field.NewString(table, "organizationCategoryNameEn")
	m.CreatedAt = field.NewTime(table, "createdAt")
	m.UpdatedAt = field.NewTime(table, "updatedAt")

	m.fillFieldMap()

	return m
}

func (m *mOrganizationCategory) WithContext(ctx context.Context) *mOrganizationCategoryDo {
	return m.mOrganizationCategoryDo.WithContext(ctx)
}

func (m mOrganizationCategory) TableName() string { return m.mOrganizationCategoryDo.TableName() }

func (m mOrganizationCategory) Alias() string { return m.mOrganizationCategoryDo.Alias() }

func (m mOrganizationCategory) Columns(cols ...field.Expr) gen.Columns {
	return m.mOrganizationCategoryDo.Columns(cols...)
}

func (m *mOrganizationCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mOrganizationCategory) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["organizationCategoryNameJa"] = m.OrganizationCategoryNameJa
	m.fieldMap["organizationCategoryNameEn"] = m.OrganizationCategoryNameEn
	m.fieldMap["createdAt"] = m.CreatedAt
	m.fieldMap["updatedAt"] = m.UpdatedAt
}

func (m mOrganizationCategory) clone(db *gorm.DB) mOrganizationCategory {
	m.mOrganizationCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mOrganizationCategory) replaceDB(db *gorm.DB) mOrganizationCategory {
	m.mOrganizationCategoryDo.ReplaceDB(db)
	return m
}

type mOrganizationCategoryDo struct{ gen.DO }

func (m mOrganizationCategoryDo) Debug() *mOrganizationCategoryDo {
	return m.withDO(m.DO.Debug())
}

func (m mOrganizationCategoryDo) WithContext(ctx context.Context) *mOrganizationCategoryDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mOrganizationCategoryDo) ReadDB() *mOrganizationCategoryDo {
	return m.Clauses(dbresolver.Read)
}

func (m mOrganizationCategoryDo) WriteDB() *mOrganizationCategoryDo {
	return m.Clauses(dbresolver.Write)
}

func (m mOrganizationCategoryDo) Session(config *gorm.Session) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Session(config))
}

func (m mOrganizationCategoryDo) Clauses(conds ...clause.Expression) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mOrganizationCategoryDo) Returning(value interface{}, columns ...string) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mOrganizationCategoryDo) Not(conds ...gen.Condition) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mOrganizationCategoryDo) Or(conds ...gen.Condition) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mOrganizationCategoryDo) Select(conds ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mOrganizationCategoryDo) Where(conds ...gen.Condition) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mOrganizationCategoryDo) Order(conds ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mOrganizationCategoryDo) Distinct(cols ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mOrganizationCategoryDo) Omit(cols ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mOrganizationCategoryDo) Join(table schema.Tabler, on ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mOrganizationCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mOrganizationCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mOrganizationCategoryDo) Group(cols ...field.Expr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mOrganizationCategoryDo) Having(conds ...gen.Condition) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mOrganizationCategoryDo) Limit(limit int) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mOrganizationCategoryDo) Offset(offset int) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mOrganizationCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mOrganizationCategoryDo) Unscoped() *mOrganizationCategoryDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mOrganizationCategoryDo) Create(values ...*model.MOrganizationCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mOrganizationCategoryDo) CreateInBatches(values []*model.MOrganizationCategory, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mOrganizationCategoryDo) Save(values ...*model.MOrganizationCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mOrganizationCategoryDo) First() (*model.MOrganizationCategory, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MOrganizationCategory), nil
	}
}

func (m mOrganizationCategoryDo) Take() (*model.MOrganizationCategory, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MOrganizationCategory), nil
	}
}

func (m mOrganizationCategoryDo) Last() (*model.MOrganizationCategory, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MOrganizationCategory), nil
	}
}

func (m mOrganizationCategoryDo) Find() ([]*model.MOrganizationCategory, error) {
	result, err := m.DO.Find()
	return result.([]*model.MOrganizationCategory), err
}

func (m mOrganizationCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MOrganizationCategory, err error) {
	buf := make([]*model.MOrganizationCategory, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mOrganizationCategoryDo) FindInBatches(result *[]*model.MOrganizationCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mOrganizationCategoryDo) Attrs(attrs ...field.AssignExpr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mOrganizationCategoryDo) Assign(attrs ...field.AssignExpr) *mOrganizationCategoryDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mOrganizationCategoryDo) Joins(fields ...field.RelationField) *mOrganizationCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mOrganizationCategoryDo) Preload(fields ...field.RelationField) *mOrganizationCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mOrganizationCategoryDo) FirstOrInit() (*model.MOrganizationCategory, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MOrganizationCategory), nil
	}
}

func (m mOrganizationCategoryDo) FirstOrCreate() (*model.MOrganizationCategory, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MOrganizationCategory), nil
	}
}

func (m mOrganizationCategoryDo) FindByPage(offset int, limit int) (result []*model.MOrganizationCategory, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mOrganizationCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mOrganizationCategoryDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mOrganizationCategoryDo) Delete(models ...*model.MOrganizationCategory) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mOrganizationCategoryDo) withDO(do gen.Dao) *mOrganizationCategoryDo {
	m.DO = *do.(*gen.DO)
	return m
}
