// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newMUserRole(db *gorm.DB, opts ...gen.DOOption) mUserRole {
	_mUserRole := mUserRole{}

	_mUserRole.mUserRoleDo.UseDB(db, opts...)
	_mUserRole.mUserRoleDo.UseModel(&model.MUserRole{})

	tableName := _mUserRole.mUserRoleDo.TableName()
	_mUserRole.ALL = field.NewAsterisk(tableName)
	_mUserRole.ID = field.NewInt32(tableName, "id")
	_mUserRole.RoleNameJa = field.NewString(tableName, "roleNameJa")
	_mUserRole.RoleNameEn = field.NewString(tableName, "roleNameEn")
	_mUserRole.CreatedAt = field.NewTime(tableName, "createdAt")
	_mUserRole.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_mUserRole.fillFieldMap()

	return _mUserRole
}

type mUserRole struct {
	mUserRoleDo mUserRoleDo

	ALL        field.Asterisk
	ID         field.Int32
	RoleNameJa field.String
	RoleNameEn field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (m mUserRole) Table(newTableName string) *mUserRole {
	m.mUserRoleDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mUserRole) As(alias string) *mUserRole {
	m.mUserRoleDo.DO = *(m.mUserRoleDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mUserRole) updateTableName(table string) *mUserRole {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.RoleNameJa = field.NewString(table, "roleNameJa")
	m.RoleNameEn = field.NewString(table, "roleNameEn")
	m.CreatedAt = field.NewTime(table, "createdAt")
	m.UpdatedAt = field.NewTime(table, "updatedAt")

	m.fillFieldMap()

	return m
}

func (m *mUserRole) WithContext(ctx context.Context) *mUserRoleDo {
	return m.mUserRoleDo.WithContext(ctx)
}

func (m mUserRole) TableName() string { return m.mUserRoleDo.TableName() }

func (m mUserRole) Alias() string { return m.mUserRoleDo.Alias() }

func (m mUserRole) Columns(cols ...field.Expr) gen.Columns { return m.mUserRoleDo.Columns(cols...) }

func (m *mUserRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mUserRole) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["roleNameJa"] = m.RoleNameJa
	m.fieldMap["roleNameEn"] = m.RoleNameEn
	m.fieldMap["createdAt"] = m.CreatedAt
	m.fieldMap["updatedAt"] = m.UpdatedAt
}

func (m mUserRole) clone(db *gorm.DB) mUserRole {
	m.mUserRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mUserRole) replaceDB(db *gorm.DB) mUserRole {
	m.mUserRoleDo.ReplaceDB(db)
	return m
}

type mUserRoleDo struct{ gen.DO }

func (m mUserRoleDo) Debug() *mUserRoleDo {
	return m.withDO(m.DO.Debug())
}

func (m mUserRoleDo) WithContext(ctx context.Context) *mUserRoleDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mUserRoleDo) ReadDB() *mUserRoleDo {
	return m.Clauses(dbresolver.Read)
}

func (m mUserRoleDo) WriteDB() *mUserRoleDo {
	return m.Clauses(dbresolver.Write)
}

func (m mUserRoleDo) Session(config *gorm.Session) *mUserRoleDo {
	return m.withDO(m.DO.Session(config))
}

func (m mUserRoleDo) Clauses(conds ...clause.Expression) *mUserRoleDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mUserRoleDo) Returning(value interface{}, columns ...string) *mUserRoleDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mUserRoleDo) Not(conds ...gen.Condition) *mUserRoleDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mUserRoleDo) Or(conds ...gen.Condition) *mUserRoleDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mUserRoleDo) Select(conds ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mUserRoleDo) Where(conds ...gen.Condition) *mUserRoleDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mUserRoleDo) Order(conds ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mUserRoleDo) Distinct(cols ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mUserRoleDo) Omit(cols ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mUserRoleDo) Join(table schema.Tabler, on ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mUserRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mUserRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mUserRoleDo) Group(cols ...field.Expr) *mUserRoleDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mUserRoleDo) Having(conds ...gen.Condition) *mUserRoleDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mUserRoleDo) Limit(limit int) *mUserRoleDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mUserRoleDo) Offset(offset int) *mUserRoleDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mUserRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mUserRoleDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mUserRoleDo) Unscoped() *mUserRoleDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mUserRoleDo) Create(values ...*model.MUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mUserRoleDo) CreateInBatches(values []*model.MUserRole, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mUserRoleDo) Save(values ...*model.MUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mUserRoleDo) First() (*model.MUserRole, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MUserRole), nil
	}
}

func (m mUserRoleDo) Take() (*model.MUserRole, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MUserRole), nil
	}
}

func (m mUserRoleDo) Last() (*model.MUserRole, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MUserRole), nil
	}
}

func (m mUserRoleDo) Find() ([]*model.MUserRole, error) {
	result, err := m.DO.Find()
	return result.([]*model.MUserRole), err
}

func (m mUserRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MUserRole, err error) {
	buf := make([]*model.MUserRole, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mUserRoleDo) FindInBatches(result *[]*model.MUserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mUserRoleDo) Attrs(attrs ...field.AssignExpr) *mUserRoleDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mUserRoleDo) Assign(attrs ...field.AssignExpr) *mUserRoleDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mUserRoleDo) Joins(fields ...field.RelationField) *mUserRoleDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mUserRoleDo) Preload(fields ...field.RelationField) *mUserRoleDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mUserRoleDo) FirstOrInit() (*model.MUserRole, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MUserRole), nil
	}
}

func (m mUserRoleDo) FirstOrCreate() (*model.MUserRole, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MUserRole), nil
	}
}

func (m mUserRoleDo) FindByPage(offset int, limit int) (result []*model.MUserRole, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mUserRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mUserRoleDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mUserRoleDo) Delete(models ...*model.MUserRole) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mUserRoleDo) withDO(do gen.Dao) *mUserRoleDo {
	m.DO = *do.(*gen.DO)
	return m
}
