// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newProjectCost(db *gorm.DB, opts ...gen.DOOption) projectCost {
	_projectCost := projectCost{}

	_projectCost.projectCostDo.UseDB(db, opts...)
	_projectCost.projectCostDo.UseModel(&model.ProjectCost{})

	tableName := _projectCost.projectCostDo.TableName()
	_projectCost.ALL = field.NewAsterisk(tableName)
	_projectCost.ProjectID = field.NewString(tableName, "projectId")
	_projectCost.Year = field.NewInt32(tableName, "year")
	_projectCost.Cost = field.NewInt32(tableName, "cost")
	_projectCost.CreatedAt = field.NewTime(tableName, "createdAt")
	_projectCost.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_projectCost.fillFieldMap()

	return _projectCost
}

type projectCost struct {
	projectCostDo projectCostDo

	ALL       field.Asterisk
	ProjectID field.String
	Year      field.Int32
	Cost      field.Int32
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p projectCost) Table(newTableName string) *projectCost {
	p.projectCostDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectCost) As(alias string) *projectCost {
	p.projectCostDo.DO = *(p.projectCostDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectCost) updateTableName(table string) *projectCost {
	p.ALL = field.NewAsterisk(table)
	p.ProjectID = field.NewString(table, "projectId")
	p.Year = field.NewInt32(table, "year")
	p.Cost = field.NewInt32(table, "cost")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *projectCost) WithContext(ctx context.Context) *projectCostDo {
	return p.projectCostDo.WithContext(ctx)
}

func (p projectCost) TableName() string { return p.projectCostDo.TableName() }

func (p projectCost) Alias() string { return p.projectCostDo.Alias() }

func (p projectCost) Columns(cols ...field.Expr) gen.Columns { return p.projectCostDo.Columns(cols...) }

func (p *projectCost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectCost) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["projectId"] = p.ProjectID
	p.fieldMap["year"] = p.Year
	p.fieldMap["cost"] = p.Cost
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
}

func (p projectCost) clone(db *gorm.DB) projectCost {
	p.projectCostDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p projectCost) replaceDB(db *gorm.DB) projectCost {
	p.projectCostDo.ReplaceDB(db)
	return p
}

type projectCostDo struct{ gen.DO }

func (p projectCostDo) Debug() *projectCostDo {
	return p.withDO(p.DO.Debug())
}

func (p projectCostDo) WithContext(ctx context.Context) *projectCostDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectCostDo) ReadDB() *projectCostDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectCostDo) WriteDB() *projectCostDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectCostDo) Session(config *gorm.Session) *projectCostDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectCostDo) Clauses(conds ...clause.Expression) *projectCostDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectCostDo) Returning(value interface{}, columns ...string) *projectCostDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectCostDo) Not(conds ...gen.Condition) *projectCostDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectCostDo) Or(conds ...gen.Condition) *projectCostDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectCostDo) Select(conds ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectCostDo) Where(conds ...gen.Condition) *projectCostDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectCostDo) Order(conds ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectCostDo) Distinct(cols ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectCostDo) Omit(cols ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectCostDo) Join(table schema.Tabler, on ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectCostDo) LeftJoin(table schema.Tabler, on ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectCostDo) RightJoin(table schema.Tabler, on ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectCostDo) Group(cols ...field.Expr) *projectCostDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectCostDo) Having(conds ...gen.Condition) *projectCostDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectCostDo) Limit(limit int) *projectCostDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectCostDo) Offset(offset int) *projectCostDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectCostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *projectCostDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectCostDo) Unscoped() *projectCostDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectCostDo) Create(values ...*model.ProjectCost) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectCostDo) CreateInBatches(values []*model.ProjectCost, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectCostDo) Save(values ...*model.ProjectCost) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectCostDo) First() (*model.ProjectCost, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectCost), nil
	}
}

func (p projectCostDo) Take() (*model.ProjectCost, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectCost), nil
	}
}

func (p projectCostDo) Last() (*model.ProjectCost, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectCost), nil
	}
}

func (p projectCostDo) Find() ([]*model.ProjectCost, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProjectCost), err
}

func (p projectCostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectCost, err error) {
	buf := make([]*model.ProjectCost, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectCostDo) FindInBatches(result *[]*model.ProjectCost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectCostDo) Attrs(attrs ...field.AssignExpr) *projectCostDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectCostDo) Assign(attrs ...field.AssignExpr) *projectCostDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectCostDo) Joins(fields ...field.RelationField) *projectCostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectCostDo) Preload(fields ...field.RelationField) *projectCostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectCostDo) FirstOrInit() (*model.ProjectCost, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectCost), nil
	}
}

func (p projectCostDo) FirstOrCreate() (*model.ProjectCost, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectCost), nil
	}
}

func (p projectCostDo) FindByPage(offset int, limit int) (result []*model.ProjectCost, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectCostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectCostDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectCostDo) Delete(models ...*model.ProjectCost) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectCostDo) withDO(do gen.Dao) *projectCostDo {
	p.DO = *do.(*gen.DO)
	return p
}
