// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newProjectSystemRelation(db *gorm.DB, opts ...gen.DOOption) projectSystemRelation {
	_projectSystemRelation := projectSystemRelation{}

	_projectSystemRelation.projectSystemRelationDo.UseDB(db, opts...)
	_projectSystemRelation.projectSystemRelationDo.UseModel(&model.ProjectSystemRelation{})

	tableName := _projectSystemRelation.projectSystemRelationDo.TableName()
	_projectSystemRelation.ALL = field.NewAsterisk(tableName)
	_projectSystemRelation.ProjectID = field.NewString(tableName, "projectId")
	_projectSystemRelation.SystemID = field.NewString(tableName, "systemId")
	_projectSystemRelation.CreatedAt = field.NewTime(tableName, "createdAt")
	_projectSystemRelation.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_projectSystemRelation.fillFieldMap()

	return _projectSystemRelation
}

type projectSystemRelation struct {
	projectSystemRelationDo projectSystemRelationDo

	ALL       field.Asterisk
	ProjectID field.String
	SystemID  field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p projectSystemRelation) Table(newTableName string) *projectSystemRelation {
	p.projectSystemRelationDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectSystemRelation) As(alias string) *projectSystemRelation {
	p.projectSystemRelationDo.DO = *(p.projectSystemRelationDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectSystemRelation) updateTableName(table string) *projectSystemRelation {
	p.ALL = field.NewAsterisk(table)
	p.ProjectID = field.NewString(table, "projectId")
	p.SystemID = field.NewString(table, "systemId")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *projectSystemRelation) WithContext(ctx context.Context) *projectSystemRelationDo {
	return p.projectSystemRelationDo.WithContext(ctx)
}

func (p projectSystemRelation) TableName() string { return p.projectSystemRelationDo.TableName() }

func (p projectSystemRelation) Alias() string { return p.projectSystemRelationDo.Alias() }

func (p projectSystemRelation) Columns(cols ...field.Expr) gen.Columns {
	return p.projectSystemRelationDo.Columns(cols...)
}

func (p *projectSystemRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectSystemRelation) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["projectId"] = p.ProjectID
	p.fieldMap["systemId"] = p.SystemID
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
}

func (p projectSystemRelation) clone(db *gorm.DB) projectSystemRelation {
	p.projectSystemRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p projectSystemRelation) replaceDB(db *gorm.DB) projectSystemRelation {
	p.projectSystemRelationDo.ReplaceDB(db)
	return p
}

type projectSystemRelationDo struct{ gen.DO }

func (p projectSystemRelationDo) Debug() *projectSystemRelationDo {
	return p.withDO(p.DO.Debug())
}

func (p projectSystemRelationDo) WithContext(ctx context.Context) *projectSystemRelationDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectSystemRelationDo) ReadDB() *projectSystemRelationDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectSystemRelationDo) WriteDB() *projectSystemRelationDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectSystemRelationDo) Session(config *gorm.Session) *projectSystemRelationDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectSystemRelationDo) Clauses(conds ...clause.Expression) *projectSystemRelationDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectSystemRelationDo) Returning(value interface{}, columns ...string) *projectSystemRelationDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectSystemRelationDo) Not(conds ...gen.Condition) *projectSystemRelationDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectSystemRelationDo) Or(conds ...gen.Condition) *projectSystemRelationDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectSystemRelationDo) Select(conds ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectSystemRelationDo) Where(conds ...gen.Condition) *projectSystemRelationDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectSystemRelationDo) Order(conds ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectSystemRelationDo) Distinct(cols ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectSystemRelationDo) Omit(cols ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectSystemRelationDo) Join(table schema.Tabler, on ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectSystemRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectSystemRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectSystemRelationDo) Group(cols ...field.Expr) *projectSystemRelationDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectSystemRelationDo) Having(conds ...gen.Condition) *projectSystemRelationDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectSystemRelationDo) Limit(limit int) *projectSystemRelationDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectSystemRelationDo) Offset(offset int) *projectSystemRelationDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectSystemRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *projectSystemRelationDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectSystemRelationDo) Unscoped() *projectSystemRelationDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectSystemRelationDo) Create(values ...*model.ProjectSystemRelation) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectSystemRelationDo) CreateInBatches(values []*model.ProjectSystemRelation, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectSystemRelationDo) Save(values ...*model.ProjectSystemRelation) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectSystemRelationDo) First() (*model.ProjectSystemRelation, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectSystemRelation), nil
	}
}

func (p projectSystemRelationDo) Take() (*model.ProjectSystemRelation, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectSystemRelation), nil
	}
}

func (p projectSystemRelationDo) Last() (*model.ProjectSystemRelation, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectSystemRelation), nil
	}
}

func (p projectSystemRelationDo) Find() ([]*model.ProjectSystemRelation, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProjectSystemRelation), err
}

func (p projectSystemRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectSystemRelation, err error) {
	buf := make([]*model.ProjectSystemRelation, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectSystemRelationDo) FindInBatches(result *[]*model.ProjectSystemRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectSystemRelationDo) Attrs(attrs ...field.AssignExpr) *projectSystemRelationDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectSystemRelationDo) Assign(attrs ...field.AssignExpr) *projectSystemRelationDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectSystemRelationDo) Joins(fields ...field.RelationField) *projectSystemRelationDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectSystemRelationDo) Preload(fields ...field.RelationField) *projectSystemRelationDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectSystemRelationDo) FirstOrInit() (*model.ProjectSystemRelation, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectSystemRelation), nil
	}
}

func (p projectSystemRelationDo) FirstOrCreate() (*model.ProjectSystemRelation, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectSystemRelation), nil
	}
}

func (p projectSystemRelationDo) FindByPage(offset int, limit int) (result []*model.ProjectSystemRelation, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectSystemRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectSystemRelationDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectSystemRelationDo) Delete(models ...*model.ProjectSystemRelation) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectSystemRelationDo) withDO(do gen.Dao) *projectSystemRelationDo {
	p.DO = *do.(*gen.DO)
	return p
}
