// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		GcasGroup:               newGcasGroup(db, opts...),
		GcasGroupSystemRelation: newGcasGroupSystemRelation(db, opts...),
		GcasGroupUserRelation:   newGcasGroupUserRelation(db, opts...),
		GcasUser:                newGcasUser(db, opts...),
		MLocalGovernment:        newMLocalGovernment(db, opts...),
		MOrganizationCategory:   newMOrganizationCategory(db, opts...),
		MUserRole:               newMUserRole(db, opts...),
		Project:                 newProject(db, opts...),
		ProjectCost:             newProjectCost(db, opts...),
		ProjectSystemRelation:   newProjectSystemRelation(db, opts...),
		SchemaMigration:         newSchemaMigration(db, opts...),
		System:                  newSystem(db, opts...),
		SystemBasicInformation:  newSystemBasicInformation(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	GcasGroup               gcasGroup
	GcasGroupSystemRelation gcasGroupSystemRelation
	GcasGroupUserRelation   gcasGroupUserRelation
	GcasUser                gcasUser
	MLocalGovernment        mLocalGovernment
	MOrganizationCategory   mOrganizationCategory
	MUserRole               mUserRole
	Project                 project
	ProjectCost             projectCost
	ProjectSystemRelation   projectSystemRelation
	SchemaMigration         schemaMigration
	System                  system
	SystemBasicInformation  systemBasicInformation
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		GcasGroup:               q.GcasGroup.clone(db),
		GcasGroupSystemRelation: q.GcasGroupSystemRelation.clone(db),
		GcasGroupUserRelation:   q.GcasGroupUserRelation.clone(db),
		GcasUser:                q.GcasUser.clone(db),
		MLocalGovernment:        q.MLocalGovernment.clone(db),
		MOrganizationCategory:   q.MOrganizationCategory.clone(db),
		MUserRole:               q.MUserRole.clone(db),
		Project:                 q.Project.clone(db),
		ProjectCost:             q.ProjectCost.clone(db),
		ProjectSystemRelation:   q.ProjectSystemRelation.clone(db),
		SchemaMigration:         q.SchemaMigration.clone(db),
		System:                  q.System.clone(db),
		SystemBasicInformation:  q.SystemBasicInformation.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		GcasGroup:               q.GcasGroup.replaceDB(db),
		GcasGroupSystemRelation: q.GcasGroupSystemRelation.replaceDB(db),
		GcasGroupUserRelation:   q.GcasGroupUserRelation.replaceDB(db),
		GcasUser:                q.GcasUser.replaceDB(db),
		MLocalGovernment:        q.MLocalGovernment.replaceDB(db),
		MOrganizationCategory:   q.MOrganizationCategory.replaceDB(db),
		MUserRole:               q.MUserRole.replaceDB(db),
		Project:                 q.Project.replaceDB(db),
		ProjectCost:             q.ProjectCost.replaceDB(db),
		ProjectSystemRelation:   q.ProjectSystemRelation.replaceDB(db),
		SchemaMigration:         q.SchemaMigration.replaceDB(db),
		System:                  q.System.replaceDB(db),
		SystemBasicInformation:  q.SystemBasicInformation.replaceDB(db),
	}
}

type queryCtx struct {
	GcasGroup               *gcasGroupDo
	GcasGroupSystemRelation *gcasGroupSystemRelationDo
	GcasGroupUserRelation   *gcasGroupUserRelationDo
	GcasUser                *gcasUserDo
	MLocalGovernment        *mLocalGovernmentDo
	MOrganizationCategory   *mOrganizationCategoryDo
	MUserRole               *mUserRoleDo
	Project                 *projectDo
	ProjectCost             *projectCostDo
	ProjectSystemRelation   *projectSystemRelationDo
	SchemaMigration         *schemaMigrationDo
	System                  *systemDo
	SystemBasicInformation  *systemBasicInformationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		GcasGroup:               q.GcasGroup.WithContext(ctx),
		GcasGroupSystemRelation: q.GcasGroupSystemRelation.WithContext(ctx),
		GcasGroupUserRelation:   q.GcasGroupUserRelation.WithContext(ctx),
		GcasUser:                q.GcasUser.WithContext(ctx),
		MLocalGovernment:        q.MLocalGovernment.WithContext(ctx),
		MOrganizationCategory:   q.MOrganizationCategory.WithContext(ctx),
		MUserRole:               q.MUserRole.WithContext(ctx),
		Project:                 q.Project.WithContext(ctx),
		ProjectCost:             q.ProjectCost.WithContext(ctx),
		ProjectSystemRelation:   q.ProjectSystemRelation.WithContext(ctx),
		SchemaMigration:         q.SchemaMigration.WithContext(ctx),
		System:                  q.System.WithContext(ctx),
		SystemBasicInformation:  q.SystemBasicInformation.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
