// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sample-micro-service-api/package-go/database/model"
)

func newSystemBasicInformation(db *gorm.DB, opts ...gen.DOOption) systemBasicInformation {
	_systemBasicInformation := systemBasicInformation{}

	_systemBasicInformation.systemBasicInformationDo.UseDB(db, opts...)
	_systemBasicInformation.systemBasicInformationDo.UseModel(&model.SystemBasicInformation{})

	tableName := _systemBasicInformation.systemBasicInformationDo.TableName()
	_systemBasicInformation.ALL = field.NewAsterisk(tableName)
	_systemBasicInformation.ID = field.NewString(tableName, "id")
	_systemBasicInformation.ProjectID = field.NewString(tableName, "projectId")
	_systemBasicInformation.CorporateNumber = field.NewString(tableName, "corporateNumber")
	_systemBasicInformation.VendorName = field.NewString(tableName, "vendorName")
	_systemBasicInformation.OperationStartDate = field.NewString(tableName, "operationStartDate")
	_systemBasicInformation.StandardizationTasks = field.NewString(tableName, "standardizationTasks")
	_systemBasicInformation.CreatedAt = field.NewTime(tableName, "createdAt")
	_systemBasicInformation.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_systemBasicInformation.fillFieldMap()

	return _systemBasicInformation
}

type systemBasicInformation struct {
	systemBasicInformationDo systemBasicInformationDo

	ALL                  field.Asterisk
	ID                   field.String
	ProjectID            field.String
	CorporateNumber      field.String
	VendorName           field.String
	OperationStartDate   field.String
	StandardizationTasks field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (s systemBasicInformation) Table(newTableName string) *systemBasicInformation {
	s.systemBasicInformationDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemBasicInformation) As(alias string) *systemBasicInformation {
	s.systemBasicInformationDo.DO = *(s.systemBasicInformationDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemBasicInformation) updateTableName(table string) *systemBasicInformation {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.ProjectID = field.NewString(table, "projectId")
	s.CorporateNumber = field.NewString(table, "corporateNumber")
	s.VendorName = field.NewString(table, "vendorName")
	s.OperationStartDate = field.NewString(table, "operationStartDate")
	s.StandardizationTasks = field.NewString(table, "standardizationTasks")
	s.CreatedAt = field.NewTime(table, "createdAt")
	s.UpdatedAt = field.NewTime(table, "updatedAt")

	s.fillFieldMap()

	return s
}

func (s *systemBasicInformation) WithContext(ctx context.Context) *systemBasicInformationDo {
	return s.systemBasicInformationDo.WithContext(ctx)
}

func (s systemBasicInformation) TableName() string { return s.systemBasicInformationDo.TableName() }

func (s systemBasicInformation) Alias() string { return s.systemBasicInformationDo.Alias() }

func (s systemBasicInformation) Columns(cols ...field.Expr) gen.Columns {
	return s.systemBasicInformationDo.Columns(cols...)
}

func (s *systemBasicInformation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemBasicInformation) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["projectId"] = s.ProjectID
	s.fieldMap["corporateNumber"] = s.CorporateNumber
	s.fieldMap["vendorName"] = s.VendorName
	s.fieldMap["operationStartDate"] = s.OperationStartDate
	s.fieldMap["standardizationTasks"] = s.StandardizationTasks
	s.fieldMap["createdAt"] = s.CreatedAt
	s.fieldMap["updatedAt"] = s.UpdatedAt
}

func (s systemBasicInformation) clone(db *gorm.DB) systemBasicInformation {
	s.systemBasicInformationDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemBasicInformation) replaceDB(db *gorm.DB) systemBasicInformation {
	s.systemBasicInformationDo.ReplaceDB(db)
	return s
}

type systemBasicInformationDo struct{ gen.DO }

func (s systemBasicInformationDo) Debug() *systemBasicInformationDo {
	return s.withDO(s.DO.Debug())
}

func (s systemBasicInformationDo) WithContext(ctx context.Context) *systemBasicInformationDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemBasicInformationDo) ReadDB() *systemBasicInformationDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemBasicInformationDo) WriteDB() *systemBasicInformationDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemBasicInformationDo) Session(config *gorm.Session) *systemBasicInformationDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemBasicInformationDo) Clauses(conds ...clause.Expression) *systemBasicInformationDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemBasicInformationDo) Returning(value interface{}, columns ...string) *systemBasicInformationDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemBasicInformationDo) Not(conds ...gen.Condition) *systemBasicInformationDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemBasicInformationDo) Or(conds ...gen.Condition) *systemBasicInformationDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemBasicInformationDo) Select(conds ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemBasicInformationDo) Where(conds ...gen.Condition) *systemBasicInformationDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemBasicInformationDo) Order(conds ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemBasicInformationDo) Distinct(cols ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemBasicInformationDo) Omit(cols ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemBasicInformationDo) Join(table schema.Tabler, on ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemBasicInformationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemBasicInformationDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemBasicInformationDo) Group(cols ...field.Expr) *systemBasicInformationDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemBasicInformationDo) Having(conds ...gen.Condition) *systemBasicInformationDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemBasicInformationDo) Limit(limit int) *systemBasicInformationDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemBasicInformationDo) Offset(offset int) *systemBasicInformationDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemBasicInformationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemBasicInformationDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemBasicInformationDo) Unscoped() *systemBasicInformationDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemBasicInformationDo) Create(values ...*model.SystemBasicInformation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemBasicInformationDo) CreateInBatches(values []*model.SystemBasicInformation, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemBasicInformationDo) Save(values ...*model.SystemBasicInformation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemBasicInformationDo) First() (*model.SystemBasicInformation, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemBasicInformation), nil
	}
}

func (s systemBasicInformationDo) Take() (*model.SystemBasicInformation, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemBasicInformation), nil
	}
}

func (s systemBasicInformationDo) Last() (*model.SystemBasicInformation, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemBasicInformation), nil
	}
}

func (s systemBasicInformationDo) Find() ([]*model.SystemBasicInformation, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemBasicInformation), err
}

func (s systemBasicInformationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemBasicInformation, err error) {
	buf := make([]*model.SystemBasicInformation, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemBasicInformationDo) FindInBatches(result *[]*model.SystemBasicInformation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemBasicInformationDo) Attrs(attrs ...field.AssignExpr) *systemBasicInformationDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemBasicInformationDo) Assign(attrs ...field.AssignExpr) *systemBasicInformationDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemBasicInformationDo) Joins(fields ...field.RelationField) *systemBasicInformationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemBasicInformationDo) Preload(fields ...field.RelationField) *systemBasicInformationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemBasicInformationDo) FirstOrInit() (*model.SystemBasicInformation, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemBasicInformation), nil
	}
}

func (s systemBasicInformationDo) FirstOrCreate() (*model.SystemBasicInformation, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemBasicInformation), nil
	}
}

func (s systemBasicInformationDo) FindByPage(offset int, limit int) (result []*model.SystemBasicInformation, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemBasicInformationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemBasicInformationDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemBasicInformationDo) Delete(models ...*model.SystemBasicInformation) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemBasicInformationDo) withDO(do gen.Dao) *systemBasicInformationDo {
	s.DO = *do.(*gen.DO)
	return s
}
