FROM node:22.14.0-alpine AS base

# This Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update both files!

FROM base AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app
RUN yarn global add turbo@1.13.4
COPY . .
RUN turbo prune app-web --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS runner
RUN apk add --no-cache \
  libc6-compat \
  # for gcloud CLI
  bash curl python3
WORKDIR /app

# Install gcloud CLI
RUN curl https://sdk.cloud.google.com > install.sh && bash install.sh --disable-prompts
ENV PATH /root/google-cloud-sdk/bin:$PATH

# First install the dependencies (as they change less often)
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN corepack enable && pnpm i --frozen-lockfile

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
COPY env.sh env.sh
COPY scripts scripts

ENV ENVSH_READ_ENV_VARS=true
ENV ENVSH_VERBOSE=true
ENV ENVSH_OUTPUT=./apps/app-web/public/__env.js
ENTRYPOINT ["./env.sh"]

CMD pnpm turbo dev --filter=app-web
